apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
        app: postgres
        tier: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: postgres
    spec:
      containers:
      - name: postgres
        image: arm64v8/postgres:11.11
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pv0001
  volumeClaimTemplates:
  - metadata:
      name: pv0001
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi