apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0001-claim
spec:
  volumeName: pv0001
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi