apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0001-claim
spec:
  storageClassName: ""
  volumeName: pv0001
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi