- name: test raspi connection
  hosts: raspi4
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: git clone fancy webpage
    ansible.builtin.git:
      repo: git@github.com:avu12/fancy-webpage.git
      dest: /home/ubuntu/fancy-webpage
      key_file: /home/ubuntu/.ssh/id_ed25519
      accept_hostkey: yes
  