- name: test raspi connection
  hosts: raspi4
  remote_user: ubuntu
  become: yes
  
  tasks:
  - name: git clone fancy webpage
    ansible.builtin.git:
      repo: git@github.com:avu12/fancy-webpage.git
      dest: /home/ubuntu/fancy-webpage
      key_file: /home/ubuntu/.ssh/id_ed25519
      accept_hostkey: yes
  - name: Build an image and push it to a private repo
    docker_image:
      path: /home/ubuntu/fancy-webpage
      name: avu12/fancy-webpage:arm64v8
      tag: arm64v8
      force: yes
      push: yes